version: '3'
services:
  php:
    build: .
    working_dir: /app
    environment:
      - GITHUB_API_TOKEN
      - YII_ENV=dev
      - YII_DEBUG=1
    ports:
      - 21000:80
    volumes:
      - ./config:/app/config:cached
      - ./src:/app/src:cached
      - ./public:/app/public:delegated
      - ./node_modules:/app/node_modules:delegated
      - ./vendor:/app/vendor:delegated
      - ./composer.json:/app/composer.json:cached
      - ./composer.lock:/app/composer.lock:cached
      - ./packages.json:/app/packages.json:cached
      #- ./runtime:/app/runtime
      - ~/.composer-docker/cache:/root/.composer/cache:delegated