version: '3'
services:
  phd:
    build: .
    environment:
      - GITHUB_API_TOKEN
      - YII_ENV=dev
      - YII_DEBUG=1
    ports:
      - 21000:80
    volumes:
      - ./:/app:delegated
      - ~/.composer-docker/cache:/root/.composer/cache:delegated

